### ISSUE TITLE
nebula runner doesn't find the nebula

### ISSUE THREAD

**Issue by noambergIL** [orbs-network/release-to-staging#9]
upload: build/node-management.json to s3://orbs-internal-staging2-ap-south-1-config/node-management.json
+ node ./helpers/nebula-runner create ./build/private/nebula-node1.json ./build/private/nebula-node2.json ./build/private/nebula-node3.json ./build/private/nebula-node4.json ./build/private/nebula-node5.json
internal/modules/cjs/loader.js:670
    throw err;
    ^

Error: Cannot find module '/usr/local/lib/node_modules/@orbs-network/orbs-nebula/lib/cli/cli'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/Users/noam/work/projects/release-to-staging/helpers/nebula-runner/index.js:2:29)
    at Module._compile (internal/modules/cjs/loader.js:816:30)

**Comment by talkol** [comment]
Please check if the problem is fixed, it's hard to reproduce your specific error but I hope it will just go away. If it doesn't please reopen
